# Use official Python runtime
FROM python:3.11-slim

# Set workdir
WORKDIR /app

# Install system deps (for psycopg2 / Postgres drivers)
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python deps
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

# Expose Render’s port (dynamic at runtime)
ENV PORT=8000

# Start FastAPI app
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port $PORT"]
